source /etc/bash_completion.d/git-prompt
source /etc/profile.d/bash_completion.sh

alias ..='cd ..'
alias ...='cd ../..'
alias g='git '
alias gd='git diff '
alias gs='git status'
alias gl='git log '
alias gc='git checkout '
alias ga='git add -p'
alias gcb='git checkout -b '
alias gpr='git pull --rebase origin master'
alias g2ob='git push origin $(git branch --show-current)'
alias pull='git pull '
alias stash='git stash '
